# Dockerfile.queue
FROM python:3.10-slim

# install required system deps (if any)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# copy in only what we need
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy all the source code
COPY . .
# delete the queueing.py file
RUN rm -f queuing.py


# expose the port your FastAPI serves on
EXPOSE 8001

# run
CMD ["python", "main.py"]
