services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 3181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"           # ← expose inside→outside
      - "39092:39092"         # ← expose outside→inside
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  queue-service:
    build:
      context: .
      dockerfile: Dockerfile.queue
    depends_on:
      - kafka
      - backend
    environment:
      # point at the container hostname "kafka"
      - KAFKA_BOOTSTRAP=kafka:9092
      - GROUP_ID=reservation-queue-service
      - MATCHES_API_URL=http://10.10.41.71:8001/api/general/matches
      - REFRESH_INTERVAL=3
      - MAX_QUEUE_SIZE=5
    ports:
      - "8002:8002"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"

  reservation:
    build:
      context: .
      dockerfile: Dockerfile.reservation
    ports:
      - "8010:8010"

  kafka_api:
    build:
      context: .
      dockerfile: Dockerfile.kafka_api
    ports:
      - "8009:8009"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-2
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8003:8003"
    depends_on:
      - backend